# Generated by Django 5.0.7 on 2024-08-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTypes',
            fields=[
                ('TID', models.AutoField(primary_key=True, serialize=False)),
                ('TypesOfMovies', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='netflix',
            name='show_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='netflix',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
